import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { compileFromFile } from 'json-schema-to-typescript';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const schemaPath = path.resolve(__dirname, 'design-ready.schema.json');
const typesPath = path.resolve(__dirname, 'types.ts');

export async function generateTypes(): Promise<void> {
  const ts = await compileFromFile(schemaPath, {
    bannerComment:
      '// This file is auto-generated by tooling/design-ready/generate-types.ts. Do not edit manually.\n',
    style: { singleQuote: true, semi: true }
  });

  const existing = await fs
    .readFile(typesPath, 'utf8')
    .catch(() => '');

  if (existing.trim() === ts.trim()) {
    return;
  }

  await fs.writeFile(typesPath, ts, 'utf8');
}

if (process.argv[1] === __filename) {
  generateTypes().catch((error) => {
    console.error('[design-ready] Failed to generate types from schema.', error);
    process.exitCode = 1;
  });
}
