// This file is auto-generated by tooling/design-ready/generate-types.ts. Do not edit manually.

/**
 * ISO-8601 date (YYYY-MM-DD) or UTC timestamp.
 */
export type ISODate = string;
export type ContractSpec = ContractSpec1 & {
  id: string;
  kind: 'http' | 'rpc' | 'event';
  module: string;
  request?: JSONSchemaRef;
  response?: JSONSchemaRef;
  event?: JSONSchemaRef;
  errors?: ErrorCase[];
  examples?: ExampleRef[];
};
export type ContractSpec1 = {
  [k: string]: unknown;
};

export interface DesignReadyDocument {
  /**
   * Epic/task identifier (e.g. EP04-T03).
   */
  id: string;
  /**
   * Human-readable summary for the design.
   */
  title: string;
  /**
   * Schema document version.
   */
  version: number;
  updated_at: ISODate;
  /**
   * @minItems 1
   */
  owners: [string, ...string[]];
  /**
   * @minItems 1
   */
  modules: [ModuleSpec, ...ModuleSpec[]];
  /**
   * @minItems 1
   */
  contracts: [ContractSpec, ...ContractSpec1[]];
  /**
   * @minItems 1
   */
  patterns: [PatternRef, ...PatternRef[]];
  risks?: string[];
  test_plan: TestPlan;
  links?: {
    adrs?: string[];
    tasks?: string[];
  };
}
export interface ModuleSpec {
  key: string;
  summary: string;
  owned_by: string;
  dependencies?: string[];
  /**
   * Exported functions or endpoints.
   *
   * @minItems 1
   */
  public_surface: [string, ...string[]];
}
export interface JSONSchemaRef {
  $ref?: string;
  type?: string;
  [k: string]: unknown;
}
export interface ErrorCase {
  code: string;
  when: string;
  http?: number;
}
export interface ExampleRef {
  name: string;
  file: string;
}
export interface PatternRef {
  id: string;
  rationale: string;
}
export interface TestPlan {
  strategy: 'component' | 'contract' | 'e2e' | 'mixed';
  /**
   * @minItems 2
   */
  acceptance: [AcceptanceCase, AcceptanceCase, ...AcceptanceCase[]];
  coverage_targets?: {
    contracts_pct?: number;
  };
}
export interface AcceptanceCase {
  id: string;
  relates_to: {
    module?: string;
    contract?: string;
  };
  description: string;
  /**
   * @minItems 1
   */
  success_criteria: [string, ...string[]];
}
